{
  try {
    get();
  }
 catch (  ExecutionException e) {
    m_port.die();
    if (e.getCause() instanceof IOException) {
      m_logger.trace("VoltPort died, probably of natural causes",e.getCause());
    }
 else {
      networkLog.error("VoltPort died due to an unexpected exception",e.getCause());
    }
  }
catch (  InterruptedException e) {
    Thread.interrupted();
    m_logger.warn("VoltPort interrupted",e);
  }
 finally {
    addToChangeList(m_port);
  }
}
