@patch.object(jenkins.Jenkins, 'jenkins_open')
def test_failed(self, jenkins_mock):
    jenkins_mock.side_effect = [json.dumps(self.node_info), None, json.dumps(self.node_info)]
    with self.assertRaises(jenkins.JenkinsException) as context_manager:
        self.j.delete_node('test_node')
    self.assertEqual(jenkins_mock.call_args_list[1][0][0].get_full_url(), self.make_url('computer/test_node/doDelete'))
    self.assertEqual(str(context_manager.exception), 'delete[test_node] failed')
    self._check_requests(jenkins_mock.call_args_list)
