{
  checkNotNull(future);
  try {
    return getUninterruptibly(future);
  }
 catch (  ExecutionException e) {
    wrapAndThrowUnchecked(e.getCause());
    throw new AssertionError();
  }
}
