{
  checkNotNull(throwable);
  boolean completedWithFailure=false;
  boolean firstTimeSeeingThisException=true;
  if (allMustSucceed) {
    completedWithFailure=setException(throwable);
    if (completedWithFailure) {
      releaseResourcesAfterFailure();
    }
 else {
      firstTimeSeeingThisException=addCausalChain(getOrInitSeenExceptions(),throwable);
    }
  }
  if (throwable instanceof Error | (allMustSucceed & !completedWithFailure & firstTimeSeeingThisException)) {
    String message=(throwable instanceof Error) ? "Input Future failed with Error" : "Got more than one input Future failure. Logging failures after the first";
    logger.log(Level.SEVERE,message,throwable);
  }
}
