{
  threadRecordFailure(t);
  t.printStackTrace();
  if (t instanceof RuntimeException)   throw (RuntimeException)t;
 else   if (t instanceof Error)   throw (Error)t;
 else {
    AssertionFailedError afe=new AssertionFailedError("unexpected exception: " + t);
    afe.initCause(t);
    throw afe;
  }
}
