def testCatchesCxxExceptionsInTearDownTestCase(self):
    self.assert_(('C++ exception with description "Standard C++ exception" thrown in TearDownTestCase()' in EX_BINARY_OUTPUT))
