{
  try {
    return super.await(2 * LONG_DELAY_MS,MILLISECONDS);
  }
 catch (  TimeoutException e) {
    throw new AssertionFailedError("timed out");
  }
catch (  Exception e) {
    AssertionFailedError afe=new AssertionFailedError("Unexpected exception: " + e);
    afe.initCause(e);
    throw afe;
  }
}
