{
  try {
    delay(millis);
  }
 catch (  InterruptedException ie) {
    AssertionFailedError afe=new AssertionFailedError("Unexpected InterruptedException");
    afe.initCause(ie);
    throw afe;
  }
}
