{
  try {
    wrapper.handleEvent(event);
  }
 catch (  InvocationTargetException e) {
    try {
      subscriberExceptionHandler.handleException(e.getCause(),new SubscriberExceptionContext(this,event,wrapper.getSubscriber(),wrapper.getMethod()));
    }
 catch (    Throwable t) {
      Logger.getLogger(EventBus.class.getName()).log(Level.SEVERE,String.format("Exception %s thrown while handling exception: %s",t,e.getCause()),t);
    }
  }
}
